### ISSUE TITLE
License tweaks

### ISSUE THREAD

**Issue by quiddity-wp** [kevandotorg/nanogenmo-2015#1]
Hi. This is a fascinating project. Good stuff. :-)

The line at https://github.com/kevandotorg/nanogenmo-2015/blob/master/novel.php#L62 doesn't specify which version of the CC-BY-SA license you're releasing the novels or the code under (I think 3.0?).

The line is also a bit confusingly written. 

You might also want to include a separate "LICENSE" file in this repo, as some other projects do, e.g. https://github.com/jasongrout/multivariable-calculus-IBL/blob/master/LICENSE

Hope that helps!

**Comment by kevandotorg** [comment]
Oh, does it not just default to some common sense interpretation if no version number is given? Wikipedia page footers don't bother to include a number, so I just followed suit.

And does it make sense to distribute code under a CC licence? Github only offered me CC0 when I was setting it up, so I shrugged and left it unlicenced. (Searching to see why there were no other CC options available, I just hit threads of people talking opaquely about how CC was inappropriate for code.)

**Comment by quiddity-wp** [comment]
Err, I'm not an expert in this area, either. However! I've asked a more technically-geeky friend who opines:

> the code can be under whatever license he wants, [but] the output needs to be CC-BY-SA 3.0 or later per https://creativecommons.org/compatiblelicenses
> IANAL but I'd guess he doesn't _need_ a licence file if the output files already say they're CC
> fwiw the reason CC licenses aren't available as options when you set up a github repo is probably that CC isn't really designed for code

He didn't recommend a specific license for the code, though... HTH anyway!

**Comment by kevandotorg** [comment]
No harm in clarifying it, so I've gone ahead and updated that line, and put the whole project under an MIT Licence. Thanks.
